"""
Python wrapper for the Z1+ external binary (Kröger, ETH Zurich).

Z1+ is NOT bundled with CondenSimAdapter.  It must be obtained separately
from the CPC library (see Z1+README.txt) and is not redistributable per
the author's distribution terms.  Once installed, place the Z1+ binary on
your PATH (or pass the path explicitly).

Reference
---------
M. Kröger, "Shortest multiple disconnected path for the analysis of
entanglements in two- and three-dimensional polymeric systems",
Comput. Phys. Commun. 168, 209-232 (2005).
doi:10.1016/j.cpc.2005.01.020

M. Kröger, "The Z1+ package: Shortest multiple disconnected path for the
analysis of entanglements in macromolecular systems",
Comput. Phys. Commun. (2022). doi:10.1016/j.cpc.2023.108998

Usage
-----
    from CondenSimAdapter.core.z1plus import Z1PlusWrapper
    from CondenSimAdapter.core.entanglement import EntanglementAnalyzer

    # Built-in Z-code (always available)
    analyzer = EntanglementAnalyzer.from_chain_meta(positions, chain_meta, box)
    report = analyzer.run()
    print(report.summary())

    # Z1+ comparison (requires Z1+ installed)
    wrapper = Z1PlusWrapper()
    if wrapper.is_available():
        z1_result = wrapper.run(positions, boundaries, box)
        print(Z1PlusWrapper.compare(report, z1_result))
    else:
        print(Z1PlusWrapper.install_instructions())
"""

from __future__ import annotations

import logging
import os
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

from .entanglement import EntanglementReport

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Z1 input-format writer
# ---------------------------------------------------------------------------


def write_z1_format(
    positions: np.ndarray,
    chain_boundaries: List[Tuple[int, int]],
    box,
    unit_scale: float = 1.0,
) -> str:
    """
    Convert bead coordinates to Z1 input format.

    Z1 file format (from Z1+README.txt)::

        Line 1: M                    (number of chains)
        Line 2: boxx boxy boxz
        Line 3: N1 N2 ... NM         (beads per chain)
        Lines 4+: x y z              (one bead per line, all chains)

    Args:
        positions:        (N_total, 3) array of bead coordinates (nm).
        chain_boundaries: List of (start, end) index tuples (end exclusive).
        box:              [Lx, Ly, Lz] in nm.
        unit_scale:       Multiply all coordinates by this factor before
                          writing. Z1+ expects coordinates in units of the
                          mean bond length (dimensionless).  For protein CG
                          systems (bond ~0.38 nm), pass unit_scale=1/0.38
                          to convert nm → bond-length units; or leave as 1.0
                          to write nm directly (works fine for Z1+).

    Returns:
        Multi-line string in Z1 format.
    """
    positions = np.asarray(positions, dtype=np.float64) * unit_scale
    box_arr = np.asarray(box, dtype=np.float64) * unit_scale

    chains = [positions[s:e] for s, e in chain_boundaries]
    chain_lengths = [len(c) for c in chains]
    M = len(chains)

    lines: List[str] = []
    lines.append(str(M))
    lines.append(f"{box_arr[0]:.5f} {box_arr[1]:.5f} {box_arr[2]:.5f}")
    lines.append(" ".join(str(n) for n in chain_lengths))
    for chain in chains:
        for bead in chain:
            lines.append(f"{bead[0]:.5f} {bead[1]:.5f} {bead[2]:.5f}")
    lines.append("")  # trailing newline
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Z1+ result parser
# ---------------------------------------------------------------------------


def _parse_z1plus_output(
    workdir: str,
    n_chains: int,
    chain_names: Optional[List[str]] = None,
) -> Dict:
    """
    Parse Z1+ output files from workdir.

    Expected output files (generated by Z1+):
        Z_values.dat      – one integer Z per line, per chain
        Lpp_values.dat    – primitive path length per chain
        Z1+summary.dat    – one summary line
    """
    names = chain_names or [f"chain-{i}" for i in range(n_chains)]

    # Z_values.dat
    z_path = os.path.join(workdir, "Z_values.dat")
    if os.path.exists(z_path):
        with open(z_path) as fh:
            z_vals = []
            for line in fh:
                line = line.strip()
                if line:
                    try:
                        z_vals.append(float(line))
                    except ValueError:
                        pass
        z_arr = np.array(z_vals[:n_chains], dtype=np.float64)
        # Pad if Z1+ produced fewer values than expected
        if len(z_arr) < n_chains:
            z_arr = np.concatenate([z_arr, np.zeros(n_chains - len(z_arr))])
    else:
        logger.warning("Z_values.dat not found in %s", workdir)
        z_arr = np.zeros(n_chains, dtype=np.float64)

    # Lpp_values.dat (optional)
    lpp_path = os.path.join(workdir, "Lpp_values.dat")
    lpp_arr: Optional[np.ndarray] = None
    if os.path.exists(lpp_path):
        with open(lpp_path) as fh:
            lpp_vals = [float(line.strip()) for line in fh if line.strip()]
        lpp_arr = np.array(lpp_vals[:n_chains], dtype=np.float64)

    # Z1+summary.dat (optional, first line is the summary)
    summary_line = ""
    summary_path = os.path.join(workdir, "Z1+summary.dat")
    if os.path.exists(summary_path):
        with open(summary_path) as fh:
            summary_line = fh.readline().strip()

    return {
        "z_values": z_arr,
        "lpp_values": lpp_arr,
        "mean_z": float(z_arr.mean()) if len(z_arr) > 0 else 0.0,
        "max_z": float(z_arr.max()) if len(z_arr) > 0 else 0.0,
        "n_entangled": int(np.sum(z_arr > 0)),
        "n_chains": n_chains,
        "chain_names": names,
        "summary_line": summary_line,
    }


# ---------------------------------------------------------------------------
# Main wrapper class
# ---------------------------------------------------------------------------


class Z1PlusWrapper:
    """
    Python interface to the Z1+ external binary.

    Z1+ (Martin Kröger, ETH Zurich) implements the full Z-code algorithm
    including node *insertion*, which can yield shorter primitive paths
    and lower Z values than the pure node-removal implementation in
    EntanglementAnalyzer.

    Z1+ must be obtained separately.  See install_instructions() for
    guidance.

    Args:
        executable: Path to the Z1+ binary.  If None, searches PATH for
                    'Z1+' and then 'Z1plus'.
    """

    def __init__(self, executable: Optional[str] = None) -> None:
        if executable is not None:
            self._exe: Optional[str] = executable
        else:
            self._exe = shutil.which("Z1+") or shutil.which("Z1plus")

    # ------------------------------------------------------------------
    # Availability check
    # ------------------------------------------------------------------

    def is_available(self) -> bool:
        """Return True if a Z1+ binary is found and executable."""
        if self._exe is None:
            return False
        p = Path(self._exe)
        return p.exists() and os.access(str(p), os.X_OK)

    @staticmethod
    def install_instructions() -> str:
        """Return a formatted string with Z1+ installation guidance."""
        return (
            "Z1+ is not found on PATH.\n\n"
            "To use Z1+ with CondenSimAdapter:\n"
            "  1. Obtain Z1+ from the CPC library or contact:\n"
            "       mk@mat.ethz.ch  (Martin Kröger, ETH Zurich)\n"
            "       https://www.complexfluids.ethz.ch/Z1+\n"
            "  2. Compile and install following the Z1+ README:\n"
            "       perl Z1+install.pl\n"
            "       cp Z1+ ~/bin/  # or any directory on your PATH\n"
            "  3. Verify installation:\n"
            "       which Z1+\n"
            "       Z1+  # should print the Z1+ banner\n"
            "  4. Re-run with Z1PlusWrapper() or pass executable='/path/to/Z1+'\n\n"
            "Note: Z1+ should not be redistributed per the author's terms.\n"
            "      Please obtain it directly from the sources above.\n"
        )

    # ------------------------------------------------------------------
    # Run
    # ------------------------------------------------------------------

    def run(
        self,
        positions: np.ndarray,
        chain_boundaries: List[Tuple[int, int]],
        box,
        chain_names: Optional[List[str]] = None,
        unit_scale: float = 1.0,
        workdir: Optional[str] = None,
        extra_args: str = "",
        timeout: int = 600,
    ) -> Optional[Dict]:
        """
        Run Z1+ on the given system and return parsed results.

        The method:
          1. Converts coordinates to Z1 format (write_z1_format).
          2. Invokes the Z1+ binary in a temporary directory.
          3. Parses Z_values.dat, Lpp_values.dat, Z1+summary.dat.
          4. Returns a results dict (or None on failure).

        Args:
            positions:        (N_total, 3) array of bead coordinates (nm).
            chain_boundaries: [(start, end), ...] index pairs.
            box:              [Lx, Ly, Lz] in nm.
            chain_names:      Optional names used in the returned dict.
            unit_scale:       Coordinate scale factor (default 1.0, nm).
            workdir:          Working directory; uses a temp dir if None.
            extra_args:       Additional command-line flags for Z1+.
            timeout:          Maximum wall-clock seconds for Z1+ (default 600).

        Returns:
            dict with keys:
              z_values   – np.ndarray, per-chain Z
              lpp_values – np.ndarray or None, primitive path lengths
              mean_z     – float
              max_z      – float
              n_entangled – int
              n_chains   – int
              chain_names – list[str]
              summary_line – str (first line of Z1+summary.dat)
            Returns None if Z1+ is not available or execution fails.
        """
        if not self.is_available():
            logger.warning("Z1+ binary not found.\n%s", self.install_instructions())
            return None

        n_chains = len(chain_boundaries)

        # Write Z1 input file
        z1_content = write_z1_format(positions, chain_boundaries, box, unit_scale)

        # Set up working directory (Z1+ writes output to CWD)
        own_tmp = workdir is None
        tmpdir: str = tempfile.mkdtemp(prefix="z1plus_") if own_tmp else workdir
        if not own_tmp:
            os.makedirs(tmpdir, exist_ok=True)

        try:
            input_path = os.path.join(tmpdir, "system.Z1")
            with open(input_path, "w") as fh:
                fh.write(z1_content)

            # Z1+ does not support absolute paths: pass just the filename
            # and run with cwd=tmpdir so Z1+ resolves it relative to CWD.
            cmd = [self._exe] + extra_args.split() + ["system.Z1"]  # type: ignore[list-item]
            logger.info("Running Z1+: %s", " ".join(cmd))

            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                cwd=tmpdir,
                timeout=timeout,
            )

            if result.returncode != 0:
                logger.error(
                    "Z1+ exited with code %d.\nstderr: %s",
                    result.returncode,
                    result.stderr[:1000],
                )
                return None

            logger.debug("Z1+ stdout: %s", result.stdout[-500:])
            return _parse_z1plus_output(tmpdir, n_chains, chain_names)

        except subprocess.TimeoutExpired:
            logger.error("Z1+ timed out after %d seconds.", timeout)
            return None
        except Exception as exc:
            logger.error("Z1+ run failed: %s", exc)
            return None
        finally:
            if own_tmp:
                import shutil as _sh

                _sh.rmtree(tmpdir, ignore_errors=True)

    # ------------------------------------------------------------------
    # Convenience constructor
    # ------------------------------------------------------------------

    @classmethod
    def from_chain_meta(
        cls,
        chain_meta: List[dict],
        executable: Optional[str] = None,
    ) -> Tuple["Z1PlusWrapper", List[Tuple[int, int]], List[str]]:
        """
        Build (wrapper, boundaries, names) from build_all_chains() output.

        Returns:
            (wrapper, boundaries, names)  ready to pass to wrapper.run().
        """
        boundaries = [(m["start"], m["end"]) for m in chain_meta]
        names = [m.get("name", f"chain-{i}") for i, m in enumerate(chain_meta)]
        return cls(executable=executable), boundaries, names

    # ------------------------------------------------------------------
    # Comparison
    # ------------------------------------------------------------------

    @staticmethod
    def compare(
        builtin: EntanglementReport,
        z1plus: Dict,
    ) -> str:
        """
        Compare built-in Z-code results with Z1+ results.

        Args:
            builtin: EntanglementReport from EntanglementAnalyzer.run().
            z1plus:  Dict returned by Z1PlusWrapper.run().

        Returns:
            Formatted comparison report as a string.
        """
        z_bi = builtin.z_values
        z_z1 = z1plus.get("z_values", np.zeros(len(z_bi), dtype=np.float64))

        n = min(len(z_bi), len(z_z1))
        z_bi = z_bi[:n]
        z_z1 = z_z1[:n]

        diff = z_bi - z_z1
        mae = float(np.abs(diff).mean())
        max_diff = float(np.abs(diff).max())
        corr: float
        if n > 1 and z_bi.std() > 0 and z_z1.std() > 0:
            corr = float(np.corrcoef(z_bi, z_z1)[0, 1])
        else:
            corr = float("nan")

        # Agreement: chains where both methods agree on Z = 0 vs Z > 0
        agree_binary = int(np.sum((z_bi > 0) == (z_z1 > 0)))

        lines = [
            "=" * 56,
            "  Z-code (built-in)  vs  Z1+  Comparison",
            "=" * 56,
            f"  Chains compared        : {n}",
            f"  Built-in mean Z        : {z_bi.mean():.2f}",
            f"  Z1+      mean Z        : {z_z1.mean():.2f}",
            f"  Mean |built-in - Z1+|  : {mae:.2f}",
            f"  Max  |built-in - Z1+|  : {max_diff:.0f}",
            f"  Pearson correlation    : {corr:.3f}",
            f"  Binary agree (Z>0?)    : {agree_binary} / {n}",
            "",
            "  Note: Built-in uses node-removal only; Z1+ also inserts",
            "  nodes, so built-in Z ≥ Z1+ in general.",
            "=" * 56,
        ]
        return "\n".join(lines)
