#!/usr/bin/env python3
"""
To Run Command

Generate production run scripts for adapter minimize output using OpenMM or AMBER.
"""

import sys
import shutil
from pathlib import Path

import click
from click_option_group import optgroup


def _print_help(ctx, param, value):
    if not value or ctx.resilient_parsing:
        return
    click.echo(ctx.get_help())
    ctx.exit()


# Default values
DEFAULT_TIMESTEP_FS = 2.0
DEFAULT_TEMPERATURE_K = 300.0
DEFAULT_PRESSURE_BAR = 1.0
DEFAULT_CUTOFF_NM = 1.2
DEFAULT_TIME_NS = 100.0
DEFAULT_TRAJ_INTERVAL_NS = 0.1
DEFAULT_LOG_INTERVAL_NS = 0.1
DEFAULT_MIN_TOLERANCE = 1.0
DEFAULT_MIN_MAX_STEPS = 5000
DEFAULT_BAROSTAT_INTERVAL = 25
GROMACS_INCLUDE_DIR = '/usr/local/gromacs/share/gromacs/top'


def get_system_name_from_yaml(yaml_path: str) -> str:
    """Read system_name from YAML config file."""
    import yaml
    path = Path(yaml_path)
    if not path.exists():
        raise FileNotFoundError(f"YAML file not found: {yaml_path}")

    with open(path, 'r') as f:
        config = yaml.safe_load(f)

    if 'system_name' not in config:
        raise KeyError(f"'system_name' field not found in YAML: {yaml_path}")

    return config['system_name']


def detect_gro_file(minimize_dir: Path) -> tuple[str, str]:
    """Detect which coordinate file to use."""
    gro_file = minimize_dir / "minimize_final_solvated.gro"
    pdb_file = minimize_dir / "minimize_final.pdb"

    if gro_file.exists():
        return ("minimize_final_solvated.gro", str(gro_file))
    elif pdb_file.exists():
        return ("minimize_final.pdb", str(pdb_file))
    else:
        raise FileNotFoundError(
            f"Neither minimize_final_solvated.gro nor minimize_final.pdb found in {minimize_dir}"
        )


def setup_production_folder(
    minimize_dir: Path,
    production_dir: Path,
    gro_name: str,
    gro_path: str,
) -> None:
    """Setup production folder with appropriate files."""
    production_dir.mkdir(parents=True, exist_ok=True)
    click.echo(f"Created production folder: {production_dir}")

    # Copy coordinate file
    shutil.copy2(gro_path, production_dir / gro_name)
    click.echo(f"Copied: {gro_name}")

    # Copy topology file
    top_file = minimize_dir / "topol.top"
    if top_file.exists():
        shutil.copy2(top_file, production_dir / "topol.top")
        click.echo(f"Copied: topol.top")
    else:
        click.echo(f"Warning: topol.top not found in {minimize_dir}")

    # Copy .ff folders (force field directories)
    for item in minimize_dir.iterdir():
        if item.is_dir() and item.name.endswith('.ff'):
            dest = production_dir / item.name
            shutil.copytree(item, dest, dirs_exist_ok=True)
            print(f"Copied: {item.name}/")


def generate_openmm_script(
    production_dir: Path,
    gro_file: str,
    total_time_ns: float,
    timestep_fs: float,
    temperature_k: float,
    is_npt: bool,
    pressure_bar: float,
    cutoff_nm: float,
    traj_interval_ps: float,
    log_interval_ps: float,
    do_minimize: bool,
    min_tolerance: float,
    min_max_steps: int,
) -> None:
    """Generate OpenMM run script in production folder."""
    # Calculate total steps: time(ns) * 1e6 / timestep(fs)
    n_steps = int(total_time_ns * 1_000_000 / timestep_fs)

    # Convert intervals from ns to steps
    traj_interval_steps = int(traj_interval_ps * 1000 / timestep_fs)
    log_interval_steps = int(log_interval_ps * 1000 / timestep_fs)

    script_content = f'''#!/usr/bin/env python3
"""
OpenMM production run script for {production_dir.name}

Auto-generated by adapter to_run
Edit the configuration parameters below to customize the simulation.
"""

# =============================================================================
# USER CONFIGURATION - Modify these values as needed
# =============================================================================

# Input files
GRO_FILE = '{gro_file}'
TOP_FILE = 'topol.top'
GROMACS_INCLUDE_DIR = '{GROMACS_INCLUDE_DIR}'

# Simulation parameters
TIMESTEP_FS = {timestep_fs}          # Timestep in femtoseconds
TEMPERATURE_K = {temperature_k}      # Temperature in Kelvin
N_STEPS = {n_steps}          # Total number of steps ({total_time_ns} ns)

# Ensemble type: True for NPT, False for NVT
RUN_NPT = {str(is_npt)}
PRESSURE_BAR = {pressure_bar}         # Pressure in bar (only used if RUN_NPT=True)
BAROSTAT_INTERVAL = {DEFAULT_BAROSTAT_INTERVAL}    # Barostat frequency

# Nonbonded parameters
CUTOFF_NM = {cutoff_nm}           # Nonbonded cutoff in nm

# Output settings
TRAJ_FILE = 'trajectory.xtc'
LOG_FILE = 'simulation.log'
REPORT_INTERVAL = {traj_interval_steps}    # Steps between trajectory writes
LOG_INTERVAL = {log_interval_steps}       # Steps between log output

# Energy minimization
DO_MINIMIZE = {str(do_minimize)}
MIN_TOLERANCE = {min_tolerance}       # Minimization tolerance
MIN_MAX_STEPS = {min_max_steps}      # Maximum minimization steps

# =============================================================================

import sys

from openmm import app, unit, LangevinMiddleIntegrator, MonteCarloBarostat
from openmm.app import Simulation, GromacsGroFile, GromacsTopFile, PME, HBonds

# Try to import XTC Reporter (available in OpenMM 7.9+)
try:
    from openmm.app import XTCReporter
    HAS_XTC = True
except ImportError:
    from openmm.app import DCDReporter as XTCReporter
    HAS_XTC = False

from openmm.app import StateDataReporter


def create_system(top):
    system = top.createSystem(
        nonbondedMethod=PME,
        nonbondedCutoff=CUTOFF_NM * unit.nanometer,
        constraints=HBonds,
        rigidWater=True,
        removeCMMotion=True
    )
    return system


def create_integrator():
    temperature = TEMPERATURE_K * unit.kelvin
    timestep = TIMESTEP_FS * unit.femtoseconds

    friction = 1.0 / unit.picosecond
    integrator = LangevinMiddleIntegrator(temperature, friction, timestep)
    return integrator


def add_barostat(system):
    if RUN_NPT:
        temperature = TEMPERATURE_K * unit.kelvin
        pressure = PRESSURE_BAR * unit.bar
        barostat = MonteCarloBarostat(pressure, temperature, BAROSTAT_INTERVAL)
        system.addForce(barostat)
        return True
    return False


def main():
    print(f"Loading input files: {{GRO_FILE}}, {{TOP_FILE}}")
    gro = GromacsGroFile(GRO_FILE)
    top = GromacsTopFile(
        TOP_FILE,
        periodicBoxVectors=gro.getPeriodicBoxVectors(),
        includeDir=GROMACS_INCLUDE_DIR
    )

    print("Creating system...")
    system = create_system(top)

    is_npt = add_barostat(system)
    ensemble = "NPT" if is_npt else "NVT"
    print(f"Running {{ensemble}} ensemble at {{TEMPERATURE_K}} K")

    print("Creating integrator...")
    integrator = create_integrator()

    simulation = Simulation(top.topology, system, integrator)
    simulation.context.setPositions(gro.positions)

    if gro.getPeriodicBoxVectors() is not None:
        simulation.context.setPeriodicBoxVectors(*gro.getPeriodicBoxVectors())

    if DO_MINIMIZE:
        print(f"Minimizing energy (tolerance={{MIN_TOLERANCE}}, max_steps={{MIN_MAX_STEPS}})...")
        simulation.minimizeEnergy(tolerance=MIN_TOLERANCE, maxIterations=MIN_MAX_STEPS)

    print(f"Using trajectory format: {{'XTC' if HAS_XTC else 'DCD'}}")
    simulation.reporters.append(
        XTCReporter(TRAJ_FILE, REPORT_INTERVAL)
    )

    with open(LOG_FILE, 'w') as f:
        simulation.reporters.append(
            StateDataReporter(
                f,
                LOG_INTERVAL,
                step=True,
                time=True,
                potentialEnergy=True,
                kineticEnergy=True,
                totalEnergy=True,
                temperature=True,
                volume=True if is_npt else False,
                density=True if is_npt else False
            )
        )

    simulation.reporters.append(
        StateDataReporter(
            sys.stdout,
            LOG_INTERVAL,
            step=True,
            potentialEnergy=True,
            temperature=True,
            volume=True if is_npt else False
        )
    )

    print(f"Starting simulation: {{N_STEPS}} steps (dt={{TIMESTEP_FS}} fs)")
    simulation.step(N_STEPS)
    print("Simulation complete!")


if __name__ == '__main__':
    main()
'''

    script_path = production_dir / "openmm_run.py"
    with open(script_path, 'w') as f:
        f.write(script_content)

    click.echo(f"Generated: openmm_run.py")
    click.echo(f"  - Total time: {total_time_ns} ns")
    click.echo(f"  - Trajectory interval: {traj_interval_ps} ps ({traj_interval_steps} steps)")
    click.echo(f"  - Log interval: {log_interval_ps} ps ({log_interval_steps} steps)")


def generate_amber_script(
    production_dir: Path,
    gro_file: str,
    total_time_ns: float,
    timestep_fs: float,
    temperature_k: float,
    is_npt: bool,
    pressure_bar: float,
    traj_interval_ps: float,
    log_interval_ps: float,
) -> None:
    """Generate AMBER input files (placeholder)."""
    click.echo("Warning: AMBER support not yet implemented.")
    click.echo("Please use --engine openmm to generate OpenMM scripts.")


@click.command('to_run', context_settings={'help_option_names': []})
@optgroup.group('CORE INPUTS')
@optgroup.option(
    '--input-file', '-f',
    type=click.Path(exists=True),
    required=True,
    help='Configuration YAML (same as CG stage)',
)
@optgroup.option(
    '--input', '-i',
    type=click.Path(),
    required=False,
    default=None,
    help='Input: minimize output directory. Default: {system_name}_minimize',
)
@optgroup.group('Simulation engine')
@optgroup.option(
    '--engine', '-e',
    type=click.Choice(['openmm', 'amber']),
    default='openmm',
    help='Simulation engine to use (default: openmm). AMBER not yet implemented.',
)
@optgroup.group('Simulation parameters')
@optgroup.option(
    '--time', '-t',
    type=float,
    default=DEFAULT_TIME_NS,
    help=f'Total simulation time in nanoseconds (default: {DEFAULT_TIME_NS})',
)
@optgroup.option(
    '--timestep',
    type=float,
    default=DEFAULT_TIMESTEP_FS,
    help=f'Timestep in femtoseconds (default: {DEFAULT_TIMESTEP_FS})',
)
@optgroup.option(
    '--temperature',
    type=float,
    default=DEFAULT_TEMPERATURE_K,
    help=f'Temperature in Kelvin (default: {DEFAULT_TEMPERATURE_K})',
)
@optgroup.option(
    '--npt',
    'ensemble',
    flag_value='npt',
    default=True,
    help='Run NPT ensemble (default)',
)
@optgroup.option(
    '--nvt',
    'ensemble',
    flag_value='nvt',
    help='Run NVT ensemble',
)
@optgroup.option(
    '--pressure',
    type=float,
    default=DEFAULT_PRESSURE_BAR,
    help=f'Pressure in bar for NPT (default: {DEFAULT_PRESSURE_BAR})',
)
@optgroup.option(
    '--cutoff',
    type=float,
    default=DEFAULT_CUTOFF_NM,
    help=f'Nonbonded cutoff in nm (default: {DEFAULT_CUTOFF_NM})',
)
@optgroup.group('Output settings')
@optgroup.option(
    '--traj-interval', '-r',
    type=float,
    default=DEFAULT_TRAJ_INTERVAL_NS,
    help=f'Trajectory output interval in ns (default: {DEFAULT_TRAJ_INTERVAL_NS})',
)
@optgroup.option(
    '--log-interval', '-l',
    type=float,
    default=DEFAULT_LOG_INTERVAL_NS,
    help=f'Log output interval in ns (default: {DEFAULT_LOG_INTERVAL_NS})',
)
@optgroup.option(
    '--output', '-o',
    type=click.Path(),
    help='Output directory (default: {system_name}_production)',
)
@optgroup.group('Energy minimization')
@optgroup.option(
    '--minimize/--no-minimize',
    default=True,
    help='Run energy minimization before production (default: True)',
)
@optgroup.option(
    '--min-tolerance',
    type=float,
    default=DEFAULT_MIN_TOLERANCE,
    help=f'Minimization tolerance (default: {DEFAULT_MIN_TOLERANCE})',
)
@optgroup.option(
    '--min-steps',
    type=int,
    default=DEFAULT_MIN_MAX_STEPS,
    help=f'Maximum minimization steps (default: {DEFAULT_MIN_MAX_STEPS})',
)
@optgroup.group('HELP')
@optgroup.option(
    '-h', '--help',
    is_flag=True,
    is_eager=True,
    expose_value=False,
    callback=_print_help,
    help='Show this message and exit.',
)
def to_run_command(
    input_file,
    input,
    engine,
    time,
    timestep,
    temperature,
    ensemble,
    pressure,
    cutoff,
    traj_interval,
    log_interval,
    output,
    minimize,
    min_tolerance,
    min_steps,
):
    """\b
    Generate production run scripts for adapter minimize output.

    \b
    This command reads the minimize output directory and generates
    appropriate run scripts for molecular dynamics simulation.

    \b
    Supported engines:
        - openmm: Generate OpenMM Python script (default)
        - amber:  Placeholder (not yet implemented)

    \b
    Examples:
        adapter to_run -f config.yaml                    # Generate OpenMM script
        adapter to_run -f config.yaml -t 200              # 200 ns simulation
        adapter to_run -f config.yaml --nvt                # NVT ensemble
        adapter to_run -f config.yaml --no-minimize       # Skip minimization
        adapter to_run -f config.yaml -o my_production    # Custom output dir
    """
    from ...src.pdb2gmx_utils import load_config_from_yaml

    # Get system_name from YAML
    system_name, _ = load_config_from_yaml(input_file)

    # Determine minimize directory
    if input is None:
        input = f"{system_name}_minimize"

    minimize_dir = Path(input)
    if not minimize_dir.exists():
        raise click.BadParameter(
            f'Minimize directory "{input}" does not exist. '
            f'Run adapter minimize first or provide correct --input path.'
        )

    # Determine output directory
    if output is None:
        output = f"{system_name}_production"
    production_dir = Path(output)

    is_npt = ensemble == 'npt'

    click.echo(f"\n{'=' * 60}")
    click.echo(f"Setup Production Run (engine: {engine})")
    click.echo(f"{'=' * 60}")

    click.echo(f"\n  System: {system_name}")
    click.echo(f"  Input: {minimize_dir}")
    click.echo(f"  Output: {production_dir}")
    click.echo(f"  Engine: {engine}")
    click.echo(f"  Ensemble: {'NPT' if is_npt else 'NVT'}")
    click.echo(f"  Temperature: {temperature} K")
    if is_npt:
        click.echo(f"  Pressure: {pressure} bar")
    click.echo(f"  Time: {time} ns")
    click.echo(f"  Timestep: {timestep} fs")
    click.echo(f"  Cutoff: {cutoff} nm")
    click.echo(f"  Trajectory interval: {traj_interval} ns")
    click.echo(f"  Log interval: {log_interval} ns")
    click.echo(f"  Minimize: {'Yes' if minimize else 'No'}")

    # Detect coordinate file
    try:
        gro_name, gro_path = detect_gro_file(minimize_dir)
    except FileNotFoundError as e:
        raise click.BadParameter(str(e))

    click.echo(f"  Coordinate file: {gro_name}")

    # Setup production folder
    setup_production_folder(minimize_dir, production_dir, gro_name, gro_path)

    # Generate run script based on engine
    if engine == 'openmm':
        generate_openmm_script(
            production_dir=production_dir,
            gro_file=gro_name,
            total_time_ns=time,
            timestep_fs=timestep,
            temperature_k=temperature,
            is_npt=is_npt,
            pressure_bar=pressure,
            cutoff_nm=cutoff,
            traj_interval_ps=traj_interval * 1000,  # Convert ns to ps
            log_interval_ps=log_interval * 1000,
            do_minimize=minimize,
            min_tolerance=min_tolerance,
            min_max_steps=min_steps,
        )
    elif engine == 'amber':
        generate_amber_script(
            production_dir=production_dir,
            gro_file=gro_name,
            total_time_ns=time,
            timestep_fs=timestep,
            temperature_k=temperature,
            is_npt=is_npt,
            pressure_bar=pressure,
            traj_interval_ps=traj_interval * 1000,
            log_interval_ps=log_interval * 1000,
        )

    click.echo(f"\n  Success! Production folder ready at:")
    click.echo(f"    {production_dir}")
    click.echo(f"\n  To run the simulation:")
    click.echo(f"    cd {production_dir}")
    if engine == 'openmm':
        click.echo(f"    python openmm_run.py")
    click.echo()
